services:
  polygonxsgdbot:
    container_name: polygon_xsgd_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./src:/app/src
